export type FaceConfig = {
  image: string[];
  x?: number;
  y?: number;
  scale?: number;
  palette?: {
    [index: string]: CanvasPattern | string;
  };
};
export const faceNorm: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "        rr                    rr        ",
    "        rr                    rr        ",
    "        rr                    rr        ",
    "        rr                    rr        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 0,
  scale: 10,
};
export const faceBlink1: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "        rr                    rr        ",
    "        rr                    rr        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 0,
  scale: 10,
};
export const faceBlink2: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 0,
  scale: 10,
};
export const faceWink1: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "         rr                     r       ",
    "         rr                    r        ",
    "         rr                    r        ",
    "         rr                     r       ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "              rrrrrrrrrrrr              ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 0,
  scale: 10,
};
export const faceWink2: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "         rr                             ",
    "         rr                             ",
    "         rr                    rr       ",
    "         rr                             ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "              rrrrrrrrrrrr              ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 0,
  scale: 10,
};
export const mouseNorm: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "             rrrrrrrrrrrrrr             ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 20,
  scale: 10,
};
export const mouseSpeak1: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "            rrrrrrrrrrrrrrrr            ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 20,
  scale: 10,
};
export const mouseSpeak2: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "             rrrrrrrrrrrrrr             ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 20,
  scale: 10,
};
export const mouseSpeak3: FaceConfig = {
  image: [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "               rrrrrrrrrr               ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
  ],
  x: 0,
  y: 20,
  scale: 10,
};
